keys:
  - &lapix age1ae5qp9szghntdenhylu8j7y4yv60szf5dta32fwrrva93cuqs3pq0qrmuw
creation_rules:
  - path_regex: [^/]+\.yaml$
    key_groups:
    - age:
      - *lapix
  - path_regex: systems/lapix/secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *lapix
  - path_regex: systems/lapix/networking/wireguard/[^/]+\.yaml$
    key_groups:
    - age:
      - *lapix
