privateKey: ENC[AES256_GCM,data:r+c5JfakRFSO8T9nJA==,iv:zxS6HUz6cJ5Vt95Anzu56Ew1qvpGOTFF/Yxe2UMBkek=,tag:NfHHQ+peNYcWHe3lPUpm2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ae5qp9szghntdenhylu8j7y4yv60szf5dta32fwrrva93cuqs3pq0qrmuw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VVBPK01kdndVaExyQlVw
            TzZQZXRWWTAxNnNZTDJlbEoza25mc0xYUENBCjY2b0pnTjdyTWg5WlVRWnZJZ1J5
            T1lWdjdZSS9ISTQvYnVvcFB6Vjhoc0kKLS0tIElSNDBHZHpucHRuMS94cmJBVVhq
            QXhqcThpcFRrVUc1M1FYU2ZBbDdTODAKaiHk4PpGsFVNeyaufKqbvVIZ/vXQqCsQ
            iJK581OM6rs65krbpFFBdGFElEGbIdnh4BAcy8UO+5y48KLwSfBXlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T09:02:43Z"
    mac: ENC[AES256_GCM,data:T84F6AhGxut1GQm88sSx55658m7XIXnMQe76fAEYBNQU9cEt0wYd+1bl+0lrUMNw9latQkJqAXBZSoiQdQPtAxQAi0xyURsrmL78xi2Zhf8d36LGh7FebI780WdcNJmYhVdqj2IgyIeKIzuFxd+SJ3C5Kr1nn7ed8TClVFLV/yU=,iv:fw4/mQMGQD2seC22Y3E8mOtJ7vrO6F+oRdQrZnyVVA4=,tag:0GrN8V17Y7GmjUaSieGbaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
